'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace IF_HistServ
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(Name:="ipostep_vP.001sap0003.in_WCSX_com.sap.b1i.vplatform.runtime_INB_WS_CALL_SYNC_XPT_"& _ 
        "INB_WS_CALL_SYNC_XPT.ipo_proc", [Namespace]:="urn:ipostep_vP.001sap0003.in_WCSX_com.sap.b1i.vplatform.runtime_INB_WS_CALL_SYNC_"& _ 
        "XPT_INB_WS_CALL_SYNC_XPT.ipo_proc", ConfigurationName:="IF_HistServ.ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYN"& _ 
        "C_XPT_INB_WS_CALL_SYNC_XPTipo_proc")>  _
    Public Interface ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación Z.HistorialDeServA no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ZHistorialDeServA(ByVal request As IF_HistServ.ZHistorialDeServARequest) As IF_HistServ.ZHistorialDeServAResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function ZHistorialDeServAAsync(ByVal request As IF_HistServ.ZHistorialDeServARequest) As System.Threading.Tasks.Task(Of IF_HistServ.ZHistorialDeServAResponse)
    End Interface
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HistorialDeServAType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private dateAField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property DateA() As String
            Get
                Return Me.dateAField
            End Get
            Set
                Me.dateAField = value
                Me.RaisePropertyChanged("DateA")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HistorialDeServAResponseType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private historialDeServAResultField() As HistorialDeServAResponseTypeRow
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute("row", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property HistorialDeServAResult() As HistorialDeServAResponseTypeRow()
            Get
                Return Me.historialDeServAResultField
            End Get
            Set
                Me.historialDeServAResultField = value
                Me.RaisePropertyChanged("HistorialDeServAResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Partial Public Class HistorialDeServAResponseTypeRow
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private cardCodeField As String
        
        Private cardNameField As String
        
        Private serieField As String
        
        Private itemNameField As String
        
        Private odometroField As String
        
        Private itemCodeField As String
        
        Private dscriptionField As String
        
        Private quantityField As String
        
        Private docNumField As String
        
        Private docDateField As String
        
        Private entryField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property CardCode() As String
            Get
                Return Me.cardCodeField
            End Get
            Set
                Me.cardCodeField = value
                Me.RaisePropertyChanged("CardCode")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property CardName() As String
            Get
                Return Me.cardNameField
            End Get
            Set
                Me.cardNameField = value
                Me.RaisePropertyChanged("CardName")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property Serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
                Me.RaisePropertyChanged("Serie")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property ItemName() As String
            Get
                Return Me.itemNameField
            End Get
            Set
                Me.itemNameField = value
                Me.RaisePropertyChanged("ItemName")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property Odometro() As String
            Get
                Return Me.odometroField
            End Get
            Set
                Me.odometroField = value
                Me.RaisePropertyChanged("Odometro")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property ItemCode() As String
            Get
                Return Me.itemCodeField
            End Get
            Set
                Me.itemCodeField = value
                Me.RaisePropertyChanged("ItemCode")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property Dscription() As String
            Get
                Return Me.dscriptionField
            End Get
            Set
                Me.dscriptionField = value
                Me.RaisePropertyChanged("Dscription")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property Quantity() As String
            Get
                Return Me.quantityField
            End Get
            Set
                Me.quantityField = value
                Me.RaisePropertyChanged("Quantity")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property DocNum() As String
            Get
                Return Me.docNumField
            End Get
            Set
                Me.docNumField = value
                Me.RaisePropertyChanged("DocNum")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property DocDate() As String
            Get
                Return Me.docDateField
            End Get
            Set
                Me.docDateField = value
                Me.RaisePropertyChanged("DocDate")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property Entry() As String
            Get
                Return Me.entryField
            End Get
            Set
                Me.entryField = value
                Me.RaisePropertyChanged("Entry")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ZHistorialDeServARequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public HistorialDeServA As IF_HistServ.HistorialDeServAType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HistorialDeServA As IF_HistServ.HistorialDeServAType)
            MyBase.New
            Me.HistorialDeServA = HistorialDeServA
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ZHistorialDeServAResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public HistorialDeServAResponse As IF_HistServ.HistorialDeServAResponseType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HistorialDeServAResponse As IF_HistServ.HistorialDeServAResponseType)
            MyBase.New
            Me.HistorialDeServAResponse = HistorialDeServAResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_procChannel
        Inherits IF_HistServ.ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_procClient
        Inherits System.ServiceModel.ClientBase(Of IF_HistServ.ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc)
        Implements IF_HistServ.ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function IF_HistServ_ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc_ZHistorialDeServA(ByVal request As IF_HistServ.ZHistorialDeServARequest) As IF_HistServ.ZHistorialDeServAResponse Implements IF_HistServ.ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc.ZHistorialDeServA
            Return MyBase.Channel.ZHistorialDeServA(request)
        End Function
        
        Public Function ZHistorialDeServA(ByVal HistorialDeServA As IF_HistServ.HistorialDeServAType) As IF_HistServ.HistorialDeServAResponseType
            Dim inValue As IF_HistServ.ZHistorialDeServARequest = New IF_HistServ.ZHistorialDeServARequest()
            inValue.HistorialDeServA = HistorialDeServA
            Dim retVal As IF_HistServ.ZHistorialDeServAResponse = CType(Me,IF_HistServ.ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc).ZHistorialDeServA(inValue)
            Return retVal.HistorialDeServAResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function IF_HistServ_ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc_ZHistorialDeServAAsync(ByVal request As IF_HistServ.ZHistorialDeServARequest) As System.Threading.Tasks.Task(Of IF_HistServ.ZHistorialDeServAResponse) Implements IF_HistServ.ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc.ZHistorialDeServAAsync
            Return MyBase.Channel.ZHistorialDeServAAsync(request)
        End Function
        
        Public Function ZHistorialDeServAAsync(ByVal HistorialDeServA As IF_HistServ.HistorialDeServAType) As System.Threading.Tasks.Task(Of IF_HistServ.ZHistorialDeServAResponse)
            Dim inValue As IF_HistServ.ZHistorialDeServARequest = New IF_HistServ.ZHistorialDeServARequest()
            inValue.HistorialDeServA = HistorialDeServA
            Return CType(Me,IF_HistServ.ipostep_vP001sap0003in_WCSX_comsapb1ivplatformruntime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPTipo_proc).ZHistorialDeServAAsync(inValue)
        End Function
    End Class
End Namespace
